# Generated by Django 5.2.3 on 2025-08-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('breaks', models.JSONField(blank=True, default=dict)),
                ('holidays', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule Configuration',
                'verbose_name_plural': 'Schedule Configuration',
            },
        ),
    ]
