# Generated by Django 5.2.3 on 2026-01-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='no_preference',
            field=models.BooleanField(default=False),
        ),
    ]
