# Generated by Django 5.2.3 on 2026-01-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_no_preference'),
        ('services', '0002_rename_highlight_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='services.service'),
        ),
    ]
