# Generated by Django 5.2.3 on 2025-12-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='user',
        ),
    ]
