# Generated by Django 5.2.3 on 2026-01-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_remove_technician_avatar_remove_technician_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='weekly_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
