# Generated by Django 5.2.3 on 2026-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_technician_weekly_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='weekly_hours',
        ),
        migrations.AddField(
            model_name='technician',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
