# Generated by Django 5.2.3 on 2026-09-20 05:16

from django.db import migrations, models


def preserve_existing_capabilities(apps, schema_editor):
    Technician = apps.get_model('technicians', 'Technician')
    Service = apps.get_model('services', 'Service')
    alias = schema_editor.connection.alias
    service_ids = list(Service.objects.using(alias).values_list('pk', flat=True))
    for technician in Technician.objects.using(alias).all():
        technician.services.set(service_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_highlight_service_description_and_more'),
        ('technicians', '0004_remove_technician_weekly_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='services.service'),
        ),
        migrations.RunPython(preserve_existing_capabilities, migrations.RunPython.noop),
    ]
