# Generated by Django 5.2.3 on 2025-08-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='highlight',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_min',
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, help_text='Image URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='target_audience',
            field=models.CharField(blank=True, default='Everyone', max_length=100),
        ),
    ]
