# Generated by Django 5.2.3 on 2025-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('French Manicure', 'French Manicure'), ('Gel Polish', 'Gel Polish'), ('Nail Art Design', 'Nail Art Design'), ('Extension with Gel', 'Extension with Gel'), ('Pedicure', 'Pedicure')], max_length=50),
        ),
    ]
